AWSTemplateFormatVersion: "2010-09-09"

Description: Template for the Auto Scaling Group

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Export VPC and ALB Stack Names"
        Parameters:
          - VpcStackName
          - ALBStackName
      - Label:
          default: "Compute Configuration"
        Parameters:
          - AmiId
          - InstanceType

Parameters:
  VpcStackName:
    Description: The name of the VPC stack
    Type: String
  
  ALBStackName:
    Description: The name of the ALB stack
    Type: String
  
  AmiId:
    Description: Region specific image from the Parameter Store
    Type: String
    Default: ami-0df8c184d5f6ae949
    AllowedValues:
      - ami-0df8c184d5f6ae949
      - ami-04b4f1a9cf54c11d0
      - ami-085ad6ae776d8f09c

  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t2.micro
      - t2.nano
      - t2.small
    Default: t2.micro

Resources:
  # Launch Template for EC2 instances
  PraticalLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: PraticalLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum install -y httpd
            service httpd start
            chkconfig httpd on
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-SecurityGroupWeb
        Monitoring:
          Enabled: true

  # Auto Scaling Group
  PraticalAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 2
      HealthCheckGracePeriod: 300
      HealthCheckType: ELB
      Cooldown: 300
      LaunchTemplate:
        LaunchTemplateId: !Ref PraticalLaunchTemplate
        Version: !GetAtt PraticalLaunchTemplate.LatestVersionNumber
      MaxSize: 4
      MinSize: 2
      TargetGroupARNs:
        - Fn::ImportValue: !Sub ${ALBStackName}-PraticalTargetGroup
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnet2
      Tags:
        - Key: Name
          Value: WebServerAutoScaling
          PropagateAtLaunch: true

  PraticalCpuUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref PraticalAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70
  
  PraticalCpuDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref PraticalAutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 30